[versions]
agp = "8.13.2"
kotlin = "2.3.0"
ksp = "2.3.4"
coreKtx = "1.17.0"
kotlinxCoroutines = "1.10.2"
kotlinxSerialization = "1.9.0"

androidxActivity = "1.12.2"
androidxLifecycle = "2.10.0"
androidxComposeBom = "2026.01.00"
androidxComposeCompiler = "1.5.8"
androidxComposeUiManifest = "1.6.7"
androidxComposeMaterial3 = "1.2.1"
androidxPagingCompose = "3.3.6"

# Navigation 3
nav3Core = "1.0.0"
lifecycleViewmodelNav3 = "2.10.0"
material3AdaptiveNav3 = "1.3.0-alpha06"

# Serialization
kotlinxSerializationCore = "1.9.0"

koin = "4.0.4"
okhttp = "5.3.2"
retrofit = "3.0.0"
timberVersion = "5.0.1"
secretsVersion = "2.0.1"
coil = "2.7.0"
vico = "2.4.1"
arrow = "2.2.1.1"

room = "2.7.1"

detekt = "1.23.8"
jacoco = "0.8.7"

androidxComposeUiTest = "1.10.1"
archCoreTestingVersion = "2.2.0"
mockkVersion = "1.14.7"
androidxTestRules = "1.7.0"
turbineVersion = "1.2.1"
kluentVersion = "1.73"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
truth = "1.4.4"

appcompat = "1.7.1"
material = "1.13.0"

[libraries]
# Support libs
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

# Kotlin Serialization
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

# Compose
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }

# Material 3
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }

# AppCompat theme
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }

# ViewModels
androidx-lifecycle-runtimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtimeTesting = { group = "androidx.lifecycle", name = "lifecycle-runtime-testing", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewModelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }

# Paging
androidx-paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "androidxPagingCompose" }

# Coil
coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

# Chart library
vico-compose-m3 = { group = "com.patrykandpatrick.vico", name = "compose-m3", version.ref = "vico" }

# UI Tests
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "androidxComposeUiTest" }
androidx-compose-ui-testManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }

# Navigation
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodelNav3" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerializationCore" }

# Koin
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose" }

# Retrofit
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }

# Gson
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }

# Timber
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timberVersion" }

# Arrow
arrow-core = { group = "io.arrow-kt", name = "arrow-core", version.ref = "arrow" }
arrow-core-retrofit = { group = "io.arrow-kt", name = "arrow-core-retrofit", version.ref = "arrow" }

# Room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

# Unit tests
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidxTestRules" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
core-testing = { group = "androidx.arch.core", name = "core-testing", version.ref = "archCoreTestingVersion" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbineVersion" }
androidx-paging-testing = { group = "androidx.paging", name = "paging-testing", version.ref = "androidxPagingCompose" }
kluent-android = { group = "org.amshove.kluent", name = "kluent-android", version.ref = "kluentVersion" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }

## MockK library
mockk = { module = "io.mockk:mockk", version.ref = "mockkVersion" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockkVersion" }
mockk-agent = { module = "io.mockk:mockk-agent", version.ref = "mockkVersion" }

detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
detekt-libraries = { module = "io.gitlab.arturbosch.detekt:detekt-rules-libraries", version.ref = "detekt" }

# Dependencies of the included build-config
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
compose-gradlePlugin = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
detekt-gradlePlugin = { group = "io.gitlab.arturbosch.detekt", name = "io.gitlab.arturbosch.detekt.gradle.plugin", version.ref = "detekt" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secretsVersion" }
deteKt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
room = { id = "androidx.room", version.ref = "room" }

# Plugins defined by this project
stocksviewercmp-android-application = { id = "stocksviewercmp.android.application", version = "unspecified" }
stocksviewercmp-android-application-compose = { id = "stocksviewercmp.android.application.compose", version = "unspecified" }
stocksviewercmp-android-application-jacoco = { id = "stocksviewercmp.android.application.jacoco", version = "unspecified" }
stocksviewercmp-android-feature = { id = "stocksviewercmp.android.feature", version = "unspecified" }
stocksviewercmp-android-library = { id = "stocksviewercmp.android.library", version = "unspecified" }
stocksviewercmp-android-library-compose = { id = "stocksviewercmp.android.library.compose", version = "unspecified" }
stocksviewercmp-android-library-jacoco = { id = "stocksviewercmp.android.library.jacoco", version = "unspecified" }
stocksviewercmp-jvm-library = { id = "stocksviewercmp.jvm.library", version = "unspecified" }
stocksviewercmp-android-koin = { id = "stocksviewercmp.android.koin", version = "unspecified" }
stocksviewercmp-detekt = { id = "stocksviewercmp.detekt", version = "unspecified" }
